# Generated by Django 4.2.7 on 2023-11-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
