# Generated by Django 4.2.6 on 2023-10-23 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors_employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_start_time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('gender', models.CharField(max_length=6, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_record', models.IntegerField(unique=True)),
                ('date_of_record', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receptionist_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receptionist_id',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_count',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_no',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_status_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_type_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='price',
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='DoctorStatus',
        ),
        migrations.DeleteModel(
            name='DoctorType',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='registry',
            name='dostor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor'),
        ),
        migrations.AddField(
            model_name='registry',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
        migrations.AddField(
            model_name='patient_card',
            name='dostor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor'),
        ),
        migrations.AddField(
            model_name='patient_card',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
        migrations.AddField(
            model_name='doctors_employment',
            name='dates_of_records',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_card'),
        ),
        migrations.AddField(
            model_name='doctors_employment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor'),
        ),
    ]
