# Generated by Django 4.2.6 on 2023-10-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_diagnoses_doctors_employment_patient_patient_card_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnoses',
            new_name='Diagnose',
        ),
        migrations.RenameModel(
            old_name='Doctors_employment',
            new_name='DoctorsEmployment',
        ),
        migrations.RenameModel(
            old_name='Patient_card',
            new_name='PatientCard',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='patientcard',
            old_name='date_of_record',
            new_name='dates_of_record',
        ),
    ]
