# Generated by Django 4.2.7 on 2023-12-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dayofweek_doctorsschedule_order_workingtime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnose',
        ),
    ]
